// ลิสต์เพลงที่เล่นได้ (121 เพลง) แก้ไข/เพิ่ม/ลบได้ที่นี่
// title = ชื่อเพลง, artist = ชื่อศิลปินที่แสดง, alias = ชื่อเรียกอื่นที่คนอาจพิมพ์
export const SONGS = [
    { title: 'ขอโทษ', artist: 'ปู พงษ์สิทธิ์' },
    { title: 'ตลอดเวลา', artist: 'ปู พงษ์สิทธิ์' },
    { title: 'อยู่ตรงนี้', artist: 'ปู พงษ์สิทธิ์' },
    { title: 'แค่นั้น', artist: 'ปู พงษ์สิทธิ์' },
    { title: 'เสมอ', artist: 'ปู พงษ์สิทธิ์' },
    { title: 'ใจเป็นนาย กายเป็นบ่าว', artist: 'เล็ก รัชเมศฐ์', alias: ['ใจเป็นนาย'] },
    { title: 'ก่อนลา', artist: 'วสันต์17' },
    { title: 'คืนจันทร์', artist: 'โลโซ' },
    { title: 'หมอกหรือควัน', artist: 'เบิร์ด ธงไชย' },
    { title: 'ให้บุญนำพา', artist: 'ไหมไทย หัวใจศิลป์' },
    { title: 'ลม', artist: 'หนุ่ม กะลา' },
    { title: 'อาจจะเป็นคนนี้', artist: 'แหวน ฐิติมา' },
    { title: 'เผลอไป', artist: 'Tattoo Colour' },
    { title: 'SuperCarCare', artist: 'Tattoo Colour', alias: ['คาแคร์', 'ซุปเปอร์คาร์แคร์'] },
    { title: 'เหลินขูน', artist: 'Txrbo', alias: ['เขิน'] },
    { title: 'ใจสั่งมา', artist: 'โลโซ' },
    { title: 'ฝนตกที่หน้าต่าง', artist: 'โลโซ', alias: ['หน้าต่าง'] },
    { title: 'ซมซาน', artist: 'โลโซ' },
    { title: 'คนมีเจ้าของ', artist: 'บังนัส ฟิวเจอร์แบนด์' },
    { title: 'ช้ำคือเรา', artist: 'นิตยา บุญสูงเนิน' },
    { title: 'คิดถึง', artist: 'Peacemaker' },
    { title: 'ให้อภัยสักครั้ง', artist: 'ซินเดอเรลล่า', alias: ['ให้อภัย', 'ให้ภัย'] },
    { title: 'ใจรัก', artist: 'สุชาติ ชวางกูร' },
    { title: 'ทางหินแห่', artist: 'ก้อง ห้วยไร่' },
    { title: 'คำขอ', artist: 'ก้อง ห้วยไร่' },
    { title: 'ซ่อยลืม', artist: 'ก้อง ห้วยไร่', alias: ['ช่วยลืม'] },
    { title: '40 Km/Hr', artist: 'Terracotta', alias: ['40 km', 'สี่สิบกิโลเมตรต่อชั่วโมง'] },
    { title: 'หนอนผีเสื้อ', artist: 'หนู มิเตอร์', alias: ['หนอนผี'] },
    { title: 'ร่มสีเทา', artist: 'วัชราวลี' },
    { title: 'คืนที่ดาวเต็มฟ้า', artist: 'โมทย์ ปราโมทย์' },
    { title: 'รักแท้ในคืนหลอกลวง', artist: 'Hyper', alias: ['รักแท้ในคืน'] },
    { title: 'หลับตา', artist: 'ชรัส เฟื่องอารมย์' },
    { title: 'ภาพฝันในจักรวาล', artist: 'เขียนไขและวานิช' },
    { title: 'หนีห่าง', artist: 'เขียนไขและวานิช' },
    { title: 'หิ่งห้อยกับตะวัน', artist: 'ไชโย ธนาวัฒน์', alias: ['หิ่งห้อย'] },
    { title: 'ผิดตั้งแต่เริ่ม (ชู้รัก)', artist: 'เล็กสเร็น', alias: ['ชู้รัก', 'ผิดตั้งแต่เริ่ม'] },
    { title: 'Avenue', artist: 'วัชราวลี' },
    { title: 'ล่องแม่ปิง', artist: 'จรัล มโนเพ็ชร' },
    { title: 'ติดตลก', artist: 'โอ๊ต ปราโมทย์' },
    { title: 'คิดถึงจัง (มาหาหน่อย)', artist: 'โอ๊ต ปราโมทย์', alias: ['คิดถึงจัง', 'มาหาหน่อย'] },
    { title: 'เดือนเพ็ญ', artist: 'คาราบาว' },
    { title: 'ก้อนหินละเมอ', artist: 'Soul After Six' },
    { title: 'แฟนตัวยง', artist: 'แทมมะริน' },
    { title: 'เพียงเธอ', artist: 'Meyou' },
    { title: 'รักแรกพบ', artist: 'Tattoo Colour' },
    { title: 'ฟ้า', artist: 'Tattoo Colour' },
    { title: 'บทสรุปสุดท้าย', artist: 'Z9', alias: ['บทสรุป'] },
    { title: 'ทักครับ', artist: 'Lipta', alias: ['ทัก'] },
    { title: 'รัก', artist: 'ปุ๊ อัญชลี' },
    { title: 'ที่คั่นหนังสือ', artist: 'Bowkylion', alias: ['sometimes'] },
    { title: 'รักเอ๋ย', artist: 'เบิร์ด ธงไชย' },
    { title: 'นางฟ้าของฉัน', artist: 'วงฟีนิกซ์' },
    { title: 'เธอคือหัวใจของฉัน', artist: 'นิก รณวีร์' },
    { title: 'หากฉันตาย', artist: '60 Miles' },
    { title: 'ที่รัก (เธอ)', artist: 'เอก สุระเชษฐ์', alias: ['ที่รัก'] },
    { title: 'เกือบ + Bad Luck', artist: 'The TOYS', alias: ['เกือบ', 'bad luck'] },
    { title: 'ลองฟังแล', artist: 'โต๋ เหน่อ' },
    { title: 'ในความคึดฮอดมีแต่เจ้าผู้เดียว', artist: 'ไมค์ ภิรมย์พร', alias: ['ในความคึดฮอด'] },
    { title: 'เข้าข้างตัวเอง (อีกแล้ว)', artist: 'ETC.', alias: ['เข้าข้างตัวเอง'] },
    { title: 'จีบ (May I)', artist: 'แหนม รณเดช', alias: ['จีบ'] },
    { title: 'แก่จนป่านนี้', artist: 'ดวงดาว เดียวดาย', alias: ['แก่จนป่านนี้คงเป็นไอ้ต้าวต่อไป', 'ไอ้ต้าว'] },
    { title: 'ทำไมต้องรักเธอ', artist: 'เอิ้น พิยะดา' },
    { title: 'Good Morning Teacher', artist: 'Atom ชนกันต์', alias: ['goodmorning', 'กู๊ดมอร์นิ่ง'] },
    { title: 'ข้างๆ', artist: 'หลุยส์ ธณวิน' },
    { title: 'เข้ากันไม่ได้', artist: 'Synkornize' },
    { title: 'ไม่ต้องรู้ว่าเราคบกันแบบไหน', artist: 'ETC.', alias: ['ไม่ต้องรู้ว่าเรา'] },
    { title: 'แอบบอกรัก', artist: 'เจ้านาย' },
    { title: 'จม', artist: 'หนุ่ม กะลา' },
    { title: 'นักประดาน้ำ', artist: 'Terracotta' },
    { title: 'หนังสือเล่มเก่า', artist: 'คิงส์ ชนาวิทย์' },
    { title: 'ไม่สมศักดิ์ศรี', artist: 'ไท ธนาวุฒิ' },
    { title: 'บ่อิน', artist: 'ก้อง ห้วยไร่' },
    { title: 'ขีดเส้นใต้', artist: 'กบ ทรงสิทธิ์' },
    { title: 'อยากให้รู้ว่ารักเธอ', artist: 'จอนนี่ อันวา' },
    { title: 'โกหกหน้าตาย', artist: 'เท่ห์ อุเทน' },
    { title: 'อาย', artist: 'สิงโต นำโชค' },
    { title: 'ทะเลใจ', artist: 'คาราบาว' },
    { title: 'วาฬเกยตื้น', artist: 'GUNGUN', alias: ['วาฬ'] },
    { title: 'รถไฟ', artist: 'Tattoo Colour' },
    { title: 'เพลงของเรา', artist: 'Tattoo Colour' },
    { title: 'รักไม่ได้', artist: 'Groove Riders' },
    { title: 'ทางของฝุ่น', artist: 'Atom ชนกันต์', alias: ['ฝุ่น', 'dust'] },
    { title: 'Please', artist: 'Atom ชนกันต์', alias: ['พลีส'] },
    { title: 'Happy Birthday', artist: 'เพลงวันเกิด', alias: ['แฮปปี้เบิร์ธเดย์', 'สุขสันต์วันเกิด', 'วันเกิด'] },
    { title: 'จมน้ำตา', artist: 'นิว จิ๋ว' },
    { title: 'คนๆนี้จะไม่ไปจากเธอ', artist: 'All For Men', alias: ['คนนี้จะไม่ไปจากเธอ'] },
    { title: 'อย่าทำอย่างนี้ไม่ว่ากับใคร', artist: 'เบิร์ด ธงไชย', alias: ['อย่าทำอย่างนี้'] },
    { title: 'ภาวนา', artist: 'Meyou' },
    { title: 'ดวงดาวแห่งรัก', artist: 'Dr.Fuu' },
    { title: 'โอ๊ย โอ๊ย', artist: 'เบน ชลาทิศ', alias: ['โอ๊ย'] },
    { title: 'ฉันรู้ดี', artist: 'spoonfulz' },
    { title: 'สะใจเธอแล้วใช่ไหม', artist: 'Legendboy', alias: ['สะใจ'] },
    { title: 'นายหญิง', artist: 'Phumin' },
    { title: 'ดาว', artist: 'pause' },
    { title: 'ระเบิดเวลา', artist: 'ศาล สานศิลป์' },
    { title: 'ไข่เน่า', artist: 'เต้ย อภิวัฒน์' },
    { title: 'มักเจ้าบักคัก', artist: 'บาส สิทธิชัย' },
    { title: 'ขีดอันตราย', artist: 'ออย แสงศิลป์' },
    { title: 'จดหมาย', artist: 'The Toys' },
    { title: 'นาฬิกาทราย', artist: 'Bowkylion' },
    { title: 'ว่าว', artist: 'มีนตรา อินทิรา' },
    { title: 'รักไปแล้ว', artist: 'แบงค์ โมเดิร์น' },
    { title: 'เมื่อไหร่จะบอก', artist: 'The Parkinson' },
    { title: 'สองใจ', artist: 'ดา เอ็นโดฟิน' },
    { title: 'ตอบกลับแหน่เด้อ', artist: 'ดิต คิตตี้', alias: ['ตอบกลับแหน่เด้อ'] },
    { title: 'ต้องโทษดาว', artist: 'เบิร์ด ธงไชย' },
    { title: 'ทำไมต้องเธอ', artist: 'เบิร์ด ธงไชย' },
    { title: 'คำที่เกินจะกล่าว', artist: 'วสันต์17' },
    { title: 'ทุกการแจ้งเตือน', artist: 'ศาล สานศิลป์' },
    { title: 'ลงใจ', artist: 'Bowkylion' },
    { title: 'สีดา', artist: 'The Rube' },
    { title: 'ตัวร้ายที่รักเธอ', artist: 'ทศกัณฐ์' },
    { title: 'Miss Call', artist: 'Senorita', alias: ['มิสคอล'] },
    { title: 'Undo', artist: 'ป๊อป ปองกูล', alias: ['อันดู'] },
    { title: 'คำถามโง่ๆ', artist: 'บอย โกสิยพงษ์' },
    { title: 'Event', artist: 'Season Five', alias: ['อีเว้นท์'] },
    { title: 'สเตตัสถืกถิ่ม', artist: 'บอย พนมไพร', alias: ['สเตตัส'] },
    { title: 'รจนาเอย', artist: 'จิ๋ว สกุณชัย', alias: ['รจนา'] },
    { title: 'พอได้เสียว', artist: 'ดิต คิตตี้' },
    { title: 'แคนฮ้างนางฟ้า', artist: 'กู่แคน' },
    { title: 'คนทางนั้น', artist: 'GiFT My Project' }
  ];
